# ***********************************************************
# * Exyzer                                                  *
# * Copyright (C) 2020-2021 Yigty.ORG; all rights reserved. *
# * Copyright (C) 2020-2021 Takym.                          *
# *                                                         *
# * distributed under the MIT License.                      *
# ***********************************************************

blank_issues_enabled: true
contact_links:
  - name: How to Contribute
    url: https://github.com/YigtyORG/Exyzer/blob/master/CONTRIBUTING.md#en
    about: Please check this page before you submit issues or PRs.
  - name: 貢献方法
    url: https://github.com/YigtyORG/Exyzer/blob/master/CONTRIBUTING.md#ja
    about: Issue または PR を作成する前に確認してください。
