# ***********************************************************
# * Exyzer                                                  *
# * Copyright (C) 2020-2022 Yigty.ORG; all rights reserved. *
# * Copyright (C) 2020-2022 Takym.                          *
# *                                                         *
# * distributed under the MIT License.                      *
# ***********************************************************

version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
