name: "Benchmark"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Benchmark:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.201
    - name: Restore dependencies
      run: dotnet restore Exyzer.sln
    # Build
    - name: Build
      run: dotnet build -c Benchmark --no-restore
    # Test
    - name: Test
      run: dotnet test -c Benchmark --no-build --verbosity normal
    - name: Save Benchmarks Results
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks-results
        path: "**/BenchmarkDotNet.Artifacts/results/*"
