name: "BuildTest"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        bc: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.201
    - name: Restore dependencies
      run: dotnet restore Exyzer.sln
    # Build
    - name: Build
      run: dotnet build -c ${{ matrix.bc }} --no-restore
    # Test
    - name: Test
      run: dotnet test -c ${{ matrix.bc }} --no-build --verbosity normal
